name: Test setup-appimage
on:
  push:
    paths:
      - action.yaml
      - scripts/**
      - .github/workflows/test.yaml
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install the AppImage Hello World binary using setup-appimage
        uses: AnimMouse/setup-appimage@main
        with:
          name: helloworld-appimage
          url: https://github.com/AnimMouse/hello-world-appimage/releases/download/v1/helloworld-appimage-x86_64.AppImage
          
      - name: Test if the AppImage Hello World binary is installed by setup-appimage
        run: helloworld-appimage